# Set working directory to store captures (ZDF) and robot poses (YAML) together as hand-eye captures are performed. The
# data collected into the working directory can later be loaded and used again for calibration.
#
# Leave the working directory empty to not store any capture files or robot poses on disk. Any hand-eye calibration data
# gathered will then be gone after shutting down the camera node.
string working_directory

# Specify the calibration object(s) to be used during this hand-eye calibration session.
HandEyeCalibrationObjects calibration_objects

---
bool success
string message
